
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace WebApplication2
{

using System;
    using System.Collections.Generic;
    
public partial class memberTableV2
{

    public int Id { get; set; }

    public string UserName { get; set; }

    public string Email { get; set; }

    public bool ConfirmEmail { get; set; }

    public string Password { get; set; }

    public string FirstName { get; set; }

    public string MiddleName { get; set; }

    public string LastName { get; set; }

    public string PhoneNumber { get; set; }

    public string OptionalPhoneNumber { get; set; }

    public string Address { get; set; }

    public string Gender { get; set; }

    public string BirthDate { get; set; }

}

}
