
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace WebApplication2
{

using System;
    using System.Collections.Generic;
    
public partial class MultipleChoiceTable
{

    public int QuestionId { get; set; }

    public string Response1 { get; set; }

    public string Response2 { get; set; }

    public string Response3 { get; set; }

    public string Response4 { get; set; }

    public string Response5 { get; set; }

    public string Response6 { get; set; }

}

}
